### PR TITLE
Race conditions when concurrently publishing messages

### PR DESCRIPTION
**Pull request by andrinheusser**
Fixes race conditions in multiple places:

- By batching frames when publishing: Method, Header, Content(s)
- By making sure all frame data is written to the send buffer before an unrelated write can happen

### CODE REVIEW

**Comment by lukebakken** [comment]
> By making sure all frame data is written to the send buffer before an unrelated write can happen

Yes, this is _critical_ for all frame types. They absolutely can't be interleaved. A publish also requires that the three frames be sequentially written to the socket.

**Comment by andrinheusser** [comment]
`error: Found 4 not formatted files in 54 files`

Sorry about that. Added a new commit with fix.

**Comment by lenkan** [comment]
Thanks guys.

I also tried another fix where I put the enforcement of sequential frames for content methods on the channel level. According to spec content frames can be interleaved with frames on other channels. So I believe that is the proper place to put the guard.

It would be really useful if you would manage to write a test in module_test/ that catches this behaviour. Iirc you should be able to tune frame max to something small, then send X amount of publish methods with large enough content and verify that it doesn't break.

Otherwise I should be able to make some time to do it until next week.

**Comment by andrinheusser** [comment]
Hey I quickly tested your branch in my test setup - still receiving frame errors. I haven't looked at the code in detail yet, but I think this happens because it still allows partial frames to be written.

There are two things addressed by this PR:

- 1. Whole Frames: When writing frames, we have to make sure we write ALL frame data to the buffer without unrelated writes happening in between. Current implementation allows for this to happen if the data can't be written to the buffer in one pass. I think this is essential, regardless of (whole) frames interleaving: We never want to send unfinished frames (followed by anything other then the rest of the frame) as this will lead to frame errors in every case. The `#guard` on the socket in my PR makes sure that another write can only happen if the current one is fully written. This is the primary reason I'm experiencing frame errors.

- 2. Batching Method, Header, Content: I got a bit paranoid - I have not yet verified that this is actually a problem. I know too little about Deno internals, but using Promise.all to separately send the method and header/content, which itself is one (or two or more if there's content) async calls to write to the connection seems dangerous.

If you think `ii.` is fine the way it is, I'm happy to just get the fix in for `i.` and deal with `ii.` if and when it actually is a problem.

I will try, once again, to write a test case. In the meantime you might be able to reproduce the errors with this setup: [Repo](https://github.com/andrinheusser/rabbitmq-frame-errors-debug/tree/deno-amqp-only)

**Pull request merged**
